services:
  - type: web
    name: luiz-portfolio-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        value: 20
